title: Useful Stuff
description: Compendium of useful stuff that i try to organize here so others have access to it as well
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


color_scheme: dark

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/MixColumns/useful-stuff" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

aux_links:
  "GitHub Repository":
    - "//github.com/MixColumns/useful-stuff"

#callouts:
#  highlight:
#    color: yellow

callouts:
  warning:
    title: Warning
    color: red